version: '3'

services:
    # php
    php:
        build:
            context: ./docker/php
            args:
                TIMEZONE: ${DOCKER_TIMEZONE}
        container_name: ${DOCKER_PROJECT_NAME}_php
        networks:
            internal:
                aliases:
                    - ${DOCKER_PROJECT_NAME}_php
        labels:
            - traefik.enable=false
        expose:
            - '9000'
        volumes:
            - .:/var/www/html
            - ./var/log/php:/var/log

    # nginx
    nginx:
        image: nginx:alpine
        container_name: ${DOCKER_PROJECT_NAME}_nginx
        labels:
            - traefik.backend=nginx
            - traefik.frontend.rule=Host:${DOCKER_FRONTEND_HOST}
            - traefik.docker.network=web
            - traefik.port=80
        networks:
            - internal
            - web
        depends_on:
            - php
            - database
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
            - ./var/log/nginx:/var/log/nginx

    # MySQL
    database:
        image: mysql:8
        container_name: ${DOCKER_PROJECT_NAME}_mysql
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        networks:
            internal:
                aliases:
                    - ${DOCKER_PROJECT_NAME}_mysql
        labels:
            - traefik.enable=false
        volumes:
            - ./var/mysql-data:/var/lib/mysql
        command: mysqld --socket="/tmp/mysql.sock" --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
            - MYSQL_USER=${DOCKER_MYSQL_USER}
            - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}

networks:
    web:
        external: true
    internal:
        external: false